### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by nine76evil** [LemmurOrg/lemmur#331]
### Device info

- OS: Android
- OS version: 12
- Device: Google Pixel 5a
- Lemmur version: 0.8.0

Unable to login to the default instance of lemmy.ml. I am able to login on Jerboa and through the browser with my username/password copied from Bitwarden. Username hangs at trying to login. Email gives an error api exception and unknown email/username. Perhaps it's not syncing?

### Steps to reproduce

1. Go to 'add account'
2. Click on 'add account'
3. Enter your username/password

### Expected behavior

Login into lemmy.ml

**Comment by chen244** [comment]
Me too, I cannot login.

**Comment by wongfeihung1984** [comment]
Same.

**Comment by rettetdemdativ** [comment]
Should be fixed with #333 , right?

**Comment by wongfeihung1984** [comment]
Nope. I tried today and I still have that "LemmyApiException couldn't_find_that_username_or_email" error message.....

**Comment by shilangyu** [comment]
> Should be fixed with #333 , right?

Yes

**Comment by nine76evil** [comment]
Been a minute but I decided to download and try again today and it's still not logging in

**Comment by daffydock** [comment]
It seems like its dead, Jim.

**Comment by russell** [comment]
i  am having the same issue, i captured this stacktrace with logcat

```
08-19 08:27:47.959 27325 31210 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'int' in type cast
08-19 08:27:47.959 27325 31210 E flutter : #0      _$$_SiteFromJson (package:lemmy_api_client/src/v3/models/source.g.dart:108)
08-19 08:27:47.959 27325 31210 E flutter : #1      new _$_Site.fromJson (package:lemmy_api_client/src/v3/models/source.freezed.dart:1524)
08-19 08:27:47.959 27325 31210 E flutter : #2      _$SiteFromJson (package:lemmy_api_client/src/v3/models/source.freezed.dart:1151)
08-19 08:27:47.959 27325 31210 E flutter : #3      new Site.fromJson (package:lemmy_api_client/src/v3/models/source.dart:101)
08-19 08:27:47.959 27325 31210 E flutter : #4      _$$_SiteViewFromJson (package:lemmy_api_client/src/v3/models/views.g.dart:83)
08-19 08:27:47.959 27325 31210 E flutter : #5      new _$_SiteView.fromJson (package:lemmy_api_client/src/v3/models/views.freezed.dart:1191)
08-19 08:27:47.959 27325 31210 E flutter : #6      _$SiteViewFromJson (package:lemmy_api_client/src/v3/models/views.freezed.dart:1010)
08-19 08:27:47.959 27325 31210 E flutter : #7      new SiteView.fromJson (package:lemmy_api_client/src/v3/models/views.dart:75)
08-19 08:27:47.959 27325 31210 E flutter : #8      _$$_FullSiteViewFromJson (package:lemmy_api_client/src/v3/models/api.g.dart:164)
08-19 08:27:47.959 27325 31210 E flutter : #9      new _$_FullSiteView.fromJson (package:lemmy_api_client/src/v3/models/api.freezed.dart:1720)
08-19 08:27:47.959 27325 31210 E flutter : #10     _$FullSiteViewFromJson (package:lemmy_api_client/src/v3/models/api.freezed.dart:1473)
08-19 08:27:47.959 27325 31210 E flutter : #11     new FullSiteView.fromJson (package:lemmy_api_client/src/v3/models/api.dart:112)
08-19 08:27:47.959 27325 31210 E flutter : #12     GetSite.responseFactory (package:lemmy_api_client/src/v3/api/site.dart:152)
08-19 08:27:47.959 27325 31210 E flutter : #13     LemmyApiV3.run (package:lemmy_api_client/src/v3/main.dart:69)
08-19 08:27:47.959 27325 31210 E flutter : <asynchronous suspension>
08-19 08:27:47.959 27325 31210 E flutter : #14     AccountsStore.addAccount (package:lemmur/stores/accounts_store.dart:203)
08-19 08:27:47.959 27325 31210 E flutter : <asynchronous suspension>
08-19 08:27:47.959 27325 31210 E flutter : #15     AddAccountPage.build.handleOnAdd (package:lemmur/pages/settings/add_account_page.dart:48)
08-19 08:27:47.959 27325 31210 E flutter : <asynchronous suspension>
08-19 08:27:47.959 27325 31210 E flutter : 
```
